#Stores charts metadata and its basic informations

apiVersion: v2
name: todo-app
description: A Helm chart for Todo List microservices application with JWT Authentication
type: application
version: 2.0.1
appVersion: "2.0.1"
keywords:
  - todo
  - microservices
  - nodejs
  - react
  - postgresql
  - jwt
  - authentication
maintainers:
  - name: Devansh Verma
    email: devanshverma911@gmail.com