apiVersion: v2
name: todo-app
description: A Helm chart for Todo List microservices application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - microservices
  - nodejs
  - react
  - postgresql
maintainers:
  - name: Devansh Verma
    email: devanshverma911@gmail.com