# values.yaml
namespace: todo-app #common namespace to create a network and communicate

postgres:
  enabled: true
  image: postgres:15-alpine
  replicas: 1
  port: 5432
  database: todo_db
  username: postgres
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

backend:
  enabled: true
  image: todo-backend:latest
  replicas: 2
  port: 5000 #service type will be clusterip by default
  imagePullPolicy: Never #uses only locally built images
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50 #cutoff cpu utilization for scaling
    targetMemoryUtilizationPercentage: 70 #cutoff memory utilization for scaling

    scaleUpStabilizationWindowSeconds: 0       #scales up immediately when threshold is crossed
    scaleUpPeriodSeconds: 15                   #checks every 15 seconds if a scale up is required or not
    scaleDownStabilizationWindowSeconds: 30    #wait for resource to be below threshold for 30sec and then scales down
    scaleDownPeriodSeconds: 15                 #checks every 15 secodns if a scale down is required or not
frontend:
  enabled: true
  image: todo-frontend:latest
  replicas: 2
  port: 80
  imagePullPolicy: Never
  service:
    type: NodePort #this needs external port action 
    nodePort: 30000 #the access nodeport on web
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
