namespace: todo-dev

postgres:
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

backend:
  replicas: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3

frontend:
  replicas: 1
  service:
    nodePort: 30001
