services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: todo-backend:latest
    container_name: todo-backend
    ports:
      - "5000:5000"
    depends_on:
     - postgres
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - todo-network
    restart: on-failure

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: todo-frontend:latest
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge
