---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: todo-backend:latest
        imagePullPolicy: Never. #Uses local images instead of pulling from registry
        ports:
        - containerPort: 5000. #Exposes to 5000 within the container
        resources:  
          requests:
            cpu: 100m     #0.1 cpu core 
            memory: 128Mi  
          limits:
            cpu: 500m      #0.5 cpu core
            memory: 512Mi
        env:
        - name: PORT
          value: "5000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:  #For non sensitive data
              name: todo-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:  #For sensitive data
              name: todo-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: JWT_SECRET

---
apiVersion: v1
kind: Service   #Provides network endpoint for backend pods
metadata:
  name: backend
  namespace: todo-app
spec:      #By default the type is ClusterIP since it needs to be accessed within the cluster itself
  selector:
    app: backend
  ports:
  - port: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: todo-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80. #Port to access within the cluster

---
apiVersion: v1
kind: Service  #Serve the static files using nginx defined in the Dockerfile
metadata:
  name: frontend
  namespace: todo-app
spec:
  type: NodePort.   #Type is nodeport so that we can access it from the web using the nodeport values
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
