#Defines the foundational config resources for the app
#Namespace is important as it will seperate our todo app from any other app that might be present in the Cluster
---            
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app  #Namespace identifier for the app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "todo_db"

---
#This is to initialise the creation of our postgres database and table on startup
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: todo-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        completed BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS idx_todos_completed ON todos(completed);

---

#Do not hardcode the sensitive data in the configmap under secret.
#Future scope can be to user kubernetes secret or external secret manager so these do not show up on version control
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: todo-app
type: Opaque #Secret type used for key-value pairs
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
