---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "todo_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: todo-app
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
