apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgres.username }}
  DB_PASSWORD: {{ .Values.postgres.password }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
